Update data_proxy.py
When API returns a error then success will not be available returning 
```
AttributeError: 'ConcatenationTaskStatus' object has no attribute '_success'
```
private properties needs to have a default value for this to work